### PR TITLE
board/PoC_finger-module

### PR DESCRIPTION
**Pull request by Ben-PH**
Implements a finger board module using keyberon matrix, debouncer, and layout semantics, checking for keypresses in a hot-loop.

Still need to look at interupt-driven event-loop, making some types generic

### CODE REVIEW

**Review by ApeDevil — APPROVED** [review]
all G

**Comment by Ben-PH** [comment]
> this is the way

image

**Comment by ApeDevil** [comment]
it is haha

**Comment by ApeDevil** [comment]
that should be also a squash merge right?

**Comment by Ben-PH** [comment]
correct. squash-merge ftw. 

It's still in draft, there are a couple of things I want to refine, and perhaps roll up an interupt driven event management into this PR as well. 

I put it up for review as an intermediate thing, and give you a chance to acclimate to this process.

**Pull request merged**
